// Generated by Skyramp v1.3.26 on 2026-06-05 09:28:40.614909009 +0000 UTC m=+1493.585407251
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output activity_summary_card_after_create.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/activity_summary_card_after_create_trace.zip

// Import of required libraries
import { test, newSkyrampPlaywrightPage, expect } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(401000);

    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:8080/login");
    await page.getByRole("textbox", { name: "Enter your email..." }).fill("admin@test.com");
    await page.getByRole("textbox", { name: "Enter your password..." }).fill("Password123!");
    const loginResponsePromise = page.waitForResponse("**/api/v3/auth/login**");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    const loginResponse = await loginResponsePromise;
    expect(loginResponse.status()).toBe(200);
    await page.waitForURL(/organizations/, { timeout: 20000 });

    await page.goto("http://localhost:8080/organizations/5745a3cd-bd40-4da5-83d8-39088c8ef1d3/projects/secret-management/020d18ef-3942-408e-8c6e-7bfc1a21b43e/overview");
    await page.waitForSelector("text=Activity", { timeout: 30000 });

    await expect(page).toHaveURL(/overview/);
    await expect(page.getByRole("heading", { name: "Project Overview" })).toBeVisible();
    await expect(page.getByText("Activity")).toBeVisible();
    await expect(page.getByText("this week")).toBeVisible();
    await expect(page.getByRole("row")).toHaveCount(2);
    await expect(page.getByRole("cell", { name: "TEST_SECRET_KEY" })).toBeVisible();
    expect(errors).toHaveLength(0);
});
