// Generated by Skyramp v1.3.26 on 2026-06-05 09:28:38.663836997 +0000 UTC m=+1491.634335249
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output activity_summary_card_initial_state.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/activity_summary_card_initial_state_trace.zip

// Import of required libraries
import { test, getValue, newSkyrampPlaywrightPage, expect } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(121000);

    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:8080/login");
    // Wait for network activities to finish
    await page.waitForTimeout(6000);


    const playwrightRequest0: Record<string, any> = {
        "email": "admin@test.com",
        "password": "Password123!"
    };

    await page.getByRole("textbox", { name: "Enter your email..." }).fill(getValue(playwrightRequest0, "email"));
    await page.getByRole("textbox", { name: "Enter your password..." }).fill(getValue(playwrightRequest0, "password"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/v3/auth/login**");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    const response0 = await responsePromise0;
    expect(response0.status()).toBe(200);

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.waitForURL(/organizations/, { timeout: 20000 });

    await page.goto("http://localhost:8080/organizations/5745a3cd-bd40-4da5-83d8-39088c8ef1d3/projects/secret-management/020d18ef-3942-408e-8c6e-7bfc1a21b43e/overview");
    await page.waitForSelector("text=Activity", { timeout: 30000 });

    await expect(page.getByRole("heading", { name: "Project Overview" })).toBeVisible();
    await expect(page.getByText("Activity")).toBeVisible();
    await expect(page.getByText("this week")).toBeVisible();
    await expect(page.getByText("created")).toBeVisible();
    await expect(page.getByText("updated")).toBeVisible();
    await expect(page.getByText("deleted")).toBeVisible();
    expect(errors).toHaveLength(0);
});
