// Generated by Skyramp v1.3.24 on 2026-06-03 09:04:45.237867866 +0000 UTC m=+403.207096127
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output admin_version_info_display.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/admin_version_info_display_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { expect, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(154000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));

    await page.goto("http://localhost:8080");
    // Wait for network activities to finish
    await page.waitForTimeout(6750);


    const playwrightRequest0: Record<string, any> = {
        "email": "admin@test.com",
        "password": "Password123!"
    };

    await page.getByRole("textbox", { name: "Enter your email..." }).fill(getValue(playwrightRequest0, "email"));
    await page.getByRole("textbox", { name: "Enter your password..." }).fill(getValue(playwrightRequest0, "password"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/v3/auth/login**");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    const response0 = await responsePromise0;
    expect(response0.status()).toBe(200);

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.goto("http://localhost:8080/admin/general");
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.goto("http://localhost:8080/admin");
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await expect(page.getByTestId("server-version")).toContainText("1.0.0");
    await expect(page.getByTestId("build-timestamp")).toContainText(/\d{4}-\d{2}-\d{2}T/);
    await expect(page.getByTestId("node-version")).toContainText("v22");
    await expect(errors).toHaveLength(0);
});
