// Generated by Skyramp v1.3.26 on 2026-06-10 22:03:11.758334157 +0000 UTC m=+1685.359615359
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output archive_secret_ui_test.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/tests/skyramp/frontend/archive_secret_flows.zip

// Import of required libraries
import { test, getValue, newSkyrampPlaywrightPage, expect } from '@skyramp/skyramp';

const pageTimeout = 30000;

async function loginUser(page) {
    const playwrightRequest0: Record<string, any> = {
        "email": "admin@test.com",
        "password": "Password123!"
    };
    await page.getByRole("textbox", { name: "Enter your email..." }).fill(getValue(playwrightRequest0, "email"));
    await page.getByRole("textbox", { name: "Enter your password..." }).fill(getValue(playwrightRequest0, "password"));
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/v3/auth/login**");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    return await responsePromise0;
}

async function createProject(page) {
    await page.getByRole("button", { name: "Secrets Management" }).click();
    await page.waitForTimeout(8000);
    await page.getByRole("button", { name: "Create Project" }).click();
    await page.getByRole("textbox", { name: "Project Name" }).fill("TestProject");
    await page.getByRole("button", { name: "Create Project" }).click();
    await page.waitForTimeout(15000);
}

async function archiveSecret(page) {
    await page.waitForTimeout(3000);
    await page.getByRole("row", { name: "TEST_ARCHIVE_SECRET" }).hover();
    await page.getByRole("button", { name: "delete-value" }).click();
    await page.getByRole("textbox", { name: "Type TEST_ARCHIVE_SECRET here" }).fill("TEST_ARCHIVE_SECRET");
    await page.getByRole("button", { name: "Archive Secret" }).click();
    await page.waitForTimeout(1500);
    const responsePromise1 = page.waitForResponse("**/api/v1/pit/batch/commit**");
    await page.getByRole("button", { name: "Save Changes" }).click();
    return await responsePromise1;
}

test('testUi', async ({ page }) => {
    test.setTimeout(3021000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const errors: string[] = [];
    page.on('pageerror', (err) => errors.push(err.message));

    await page.goto("http://localhost:8080/login");
    // Wait for network activities to finish
    await page.waitForTimeout(6750);

    const response0 = await loginUser(page);
    expect(response0.status()).toBe(200);

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await createProject(page);

    const response1 = await archiveSecret(page);
    expect(response1.status()).toBe(200);
    await expect(page.getByRole("alert")).toHaveText("Changes saved successfully");
    await expect(page.getByRole("textbox", { name: "TEST_ARCHIVE_SECRET" })).not.toBeVisible();

    // Wait for network activities to finish
    await page.waitForTimeout(18868);

    await page.getByRole("button", { name: "Trash" }).click();
    await page.getByRole("button", { name: "Trash" }).click();
    await page.getByRole("button", { name: "Trash" }).click();
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise2 = page.waitForResponse("**/api/v1/secrets/**/restore**");
    await page.getByRole("button", { name: "Restore" }).click();
    const response2 = await responsePromise2;

    // Wait for network activities to finish
    await page.waitForTimeout(9928);

    await page.getByRole("button", { name: "Trash" }).click();

    expect(errors).toHaveLength(0);
});
