// Generated by Skyramp v1.3.25 on 2026-06-04 18:07:23.123238049 +0000 UTC m=+920.424698864
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output secret_description_sidebar.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/secret_description_sidebar_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(188000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));

    await page.goto("http://localhost:8080/login");
    await page.getByRole("textbox", { name: "Enter your email..." }).fill("admin@test.com");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    await page.getByRole("textbox", { name: "Enter your password..." }).fill("Password123!");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    await page.goto("http://localhost:8080/organizations/3bc2fcb9-fca1-40f7-9719-fc120046b277/projects/secret-management/82dd1fb6-8503-4017-871e-466837f24870/secrets/dev");
    await page.waitForLoadState('networkidle');
    await page.getByRole("heading", { name: "Secrets Management" }).waitFor({ state: 'visible', timeout: 10000 });
    await expect(page.getByRole("heading", { name: "Secrets Management" })).toBeVisible();
    await page.getByRole("button", { name: "more" }).click();
    await expect(page.getByRole("dialog")).toBeVisible();
    await page.getByRole("textbox", { name: "describe what this secret is" }).fill("Database password for production PostgreSQL instance");
    await expect(page.getByRole("textbox", { name: "describe what this secret is" })).toHaveValue("Database password for production PostgreSQL instance");
    await page.getByRole("button", { name: "Close" }).click();
    await expect(page.getByRole("dialog")).not.toBeVisible();

    expect(errors).toHaveLength(0);
});
