// Generated by Skyramp v1.3.25 on 2026-06-04 18:07:23.897463794 +0000 UTC m=+921.198924619
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output secret_description_limit.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/secret_description_limit_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(138000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));

    await page.goto("http://localhost:8080/login");
    await page.getByRole("textbox", { name: "Enter your email..." }).fill("admin@test.com");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    await page.getByRole("textbox", { name: "Enter your password..." }).fill("Password123!");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    await page.goto("http://localhost:8080/organizations/3bc2fcb9-fca1-40f7-9719-fc120046b277/projects/secret-management/82dd1fb6-8503-4017-871e-466837f24870/secrets/dev");
    await page.waitForLoadState('networkidle');
    await page.locator('text=Secrets Management').waitFor({ state: 'visible', timeout: 10000 });
    await page.getByRole("button", { name: "more" }).click();
    await expect(page.getByRole("dialog")).toBeVisible();
    await page.getByRole("textbox", { name: "describe what this secret is" }).fill("This secret description tests the maximum character limit enforced by the textarea. The description field supports up to five hundred characters of text. This ensures long descriptions documenting the purpose, usage context, rotation schedule, and ownership of secrets are properly capped at the limit set by the API validation rule and the frontend textarea maxLength attribute to prevent overflow issues.");
    await expect(page.getByRole("textbox", { name: "describe what this secret is" })).toHaveValue("This secret description tests the maximum character limit enforced by the textarea. The description field supports up to five hundred characters of text. This ensures long descriptions documenting the purpose, usage context, rotation schedule, and ownership of secrets are properly capped at the limit set by the API validation rule and the frontend textarea maxLength attribute to prevent overflow issues.");
    await page.getByRole("button", { name: "Close" }).click();
    await expect(page.getByRole("dialog")).not.toBeVisible();

    expect(errors).toHaveLength(0);
});
