// Generated by Skyramp v1.3.25 on 2026-06-04 18:07:21.287300423 +0000 UTC m=+918.588761248
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output secret_description_add.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/secret_description_add_trace.zip

// Import of required libraries
import { test, expect, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(1137000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));

    await page.goto("http://localhost:8080/login");
    // Wait for network activities to finish
    await page.waitForTimeout(9000);


    const playwrightRequest0: Record<string, any> = {
        "email": "admin@test.com",
        "password": "Password123!"
    };

    await page.getByRole("textbox", { name: "Enter your email..." }).fill(getValue(playwrightRequest0, "email"));
    await page.getByRole("button", { name: "Continue with Email" }).click();
    await page.getByRole("textbox", { name: "Enter your password..." }).fill(getValue(playwrightRequest0, "password"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/v3/auth/login**");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    const response0 = await responsePromise0;
    expect(response0.status()).toBe(200);

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.getByRole("button", { name: "Secrets Management" }).click();
    await page.getByRole("button", { name: "Create Project" }).click();
    await page.getByRole("textbox", { name: "Project Name" }).fill("TestProject");
    await page.getByRole("button", { name: "Create Project" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(7851);

    await page.getByText("Add a New Secret").click();
    await page.getByRole("textbox", { name: "Type your secret name" }).fill("TEST_SECRET");
    await page.getByRole("textbox", { name: "secret value" }).fill("test-value-123");
    await page.getByRole("button", { name: "Create Secret" }).click();
    await page.getByRole("button", { name: "more" }).click();
    await page.getByRole("textbox", { name: "describe what this secret is" }).fill("API key for the test service authentication endpoint");
    await expect(page.getByRole("textbox", { name: "describe what this secret is" })).toHaveValue("API key for the test service authentication endpoint");
    await page.getByRole("button", { name: "Close" }).click();
    await expect(page.getByRole("dialog")).not.toBeVisible();

    expect(errors).toHaveLength(0);
});
