// Generated by Skyramp v1.3.25 on 2026-06-03 21:18:49.044273722 +0000 UTC m=+527.216911710
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output server_version_development_default.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/server_version_development_default_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(69000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const errors: Error[] = [];
    page.on('pageerror', (error) => errors.push(error));

    await page.goto("http://localhost:8080/organizations/175b2cbf-621f-411e-a228-87ce70a57bb2/projects");
    await page.getByRole("textbox", { name: "Enter your email..." }).fill("admin@test.com");
    await page.getByRole("textbox", { name: "Enter your password..." }).fill("Password123!");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    await page.getByRole("link", { name: "Server Console" }).click();
    await page.waitForURL("**/admin");
    await expect(page).toHaveURL(/\/admin/);
    await page.waitForSelector("text=Server Version");
    await expect(page.getByRole("heading", { name: "General" })).toHaveText("General");
    expect(errors).toHaveLength(0);
});
