// Generated by Skyramp v1.3.24 on 2026-06-03 09:04:48.606122693 +0000 UTC m=+406.575350954
// Command: skyramp generate contract rest http://localhost:8080/api/status/version \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--method GET \
// 		--output contract_get_status_version.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/backend \
// 		--overwrite \
// 		--provider \
// 		--response-status-code 200 \
// 		--runtime local

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8080");

// contract test for /api/status/version GET
test('testVersionGet', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Execute Request
    const versionGetResponse = await client.sendRequest({
        url: URL,
        path: "/api/status/version",
        method: "GET",
        headers: headers
    });

    // Generated Assertions
    expect(versionGetResponse.statusCode, 'status code').toBe(200);
    expect(getValue(versionGetResponse, "version")).toBe("1.0.0");
    expect(getValue(versionGetResponse, "buildTimestamp")).toMatch(/^\d{4}-\d{2}-\d{2}T/);
    expect(getValue(versionGetResponse, "nodeVersion")).toMatch(/^v\d+/);
});
