// Generated by Skyramp v1.3.26 on 2026-06-10 22:00:03.506205656 +0000 UTC m=+1633.582765395
// Command: skyramp generate integration rest \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--output secret_favorite_cascade_delete_integration_test.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/backend \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/infisical/infisical/tests/skyramp/backend/scenario_secret_favorite_cascade_delete.json

// Import of required libraries
import { test, expect, SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
let URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:4000");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Declaration of variables
    const projectId = "a6aeaf5f-7259-4212-81af-8b3414e3a786";
    let raw = "SKYRAMP_FAV_S3";

    // Request Body
    const rawPostRequestBody = `{
            "environment": "dev",
            "secretValue": "scenario_test_val",
            "workspaceId": "a6aeaf5f-7259-4212-81af-8b3414e3a786"
        }`

    // Execute Request
    let rawPostResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/api/v3/secrets/raw/{raw}",
        method:"POST",
        body:rawPostRequestBody,
        headers:headers,
        pathParams:{"raw": raw}
    });

    // Generated Assertions
    expect(rawPostResponse.statusCode, 'status code').toBe(200);
    expect(getValue(rawPostResponse, "secret.id")).toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i);
    expect(getValue(rawPostResponse, "secret.secretKey")).toBe("SKYRAMP_FAV_S3");
    expect(getValue(rawPostResponse, "secret.workspace")).toBe(projectId);

    const secretId = getValue(rawPostResponse, "secret.id") as string;

    // Request Body
    const favoritePutRequestBody = `{
            "isFavorite": true,
            "projectId": "a6aeaf5f-7259-4212-81af-8b3414e3a786"
        }`

    // Execute Request
    let favoritePutResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/api/v1/secrets/{secrets}/favorite",
        method:"PUT",
        body:favoritePutRequestBody,
        headers:headers,
        pathParams:{"secrets": secretId}
    });

    // Generated Assertions
    expect(favoritePutResponse.statusCode, 'status code').toBe(200);
    expect(getValue(favoritePutResponse, "isFavorite")).toBe(true);

    // Execute Request
    let favoritesGetResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/api/v1/secrets/favorites",
        method:"GET",
        headers:headers,
        queryParams:{"projectId": [projectId]}
    });

    // Generated Assertions
    expect(favoritesGetResponse.statusCode, 'status code').toBe(200);
    expect(getValue(favoritesGetResponse, "favoriteSecretIds.0")).toBe(secretId);
    expect(getValue(favoritesGetResponse, "favoriteSecretIds.1")).toBeNull();

    // Request Body
    const rawDeleteRequestBody = `{
            "environment": "dev",
            "secretPath": "/",
            "workspaceId": "a6aeaf5f-7259-4212-81af-8b3414e3a786"
        }`

    // Execute Request
    let rawDeleteResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/api/v3/secrets/raw/{raw}",
        method:"DELETE",
        body:rawDeleteRequestBody,
        headers:headers,
        pathParams:{"raw": raw}
    });

    // Generated Assertions
    expect(rawDeleteResponse.statusCode, 'status code').toBe(200);
    expect(getValue(rawDeleteResponse, "secret.id")).toBe(secretId);
    expect(getValue(rawDeleteResponse, "secret.secretKey")).toBe("SKYRAMP_FAV_S3");

    // Execute Request
    let favoritesGet1Response = await client.sendRequest({
        url:URL_localhost,
        path:"/api/v1/secrets/favorites",
        method:"GET",
        headers:headers,
        queryParams:{"projectId": [projectId]}
    });

    // Generated Assertions
    expect(favoritesGet1Response.statusCode, 'status code').toBe(200);
    expect(getValue(favoritesGet1Response, "favoriteSecretIds.0")).toBeNull();
});

