// Generated by Skyramp v1.3.25 on 2026-06-03 21:21:02.58928497 +0000 UTC m=+660.761922938
// Command: skyramp generate contract rest http://localhost:4000/api/status/version \
// 		--api-schema http://localhost:4000/api/docs/json \
// 		--framework playwright \
// 		--language typescript \
// 		--method GET \
// 		--output status_version_contract_test.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/backend \
// 		--overwrite \
// 		--provider \
// 		--response-status-code 200 \
// 		--runtime local

// Import of required libraries
import { test, expect, SkyrampClient, checkSchema, getBaseUrl, getResponseValue } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:4000");

// contract test for /api/status/version GET
test('testVersionGet', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Expected Response Body
    const expectedVersionGetResponseBody: string = `{
        "nodeVersion": "string",
        "version": "string"
    }`;

    // Execute Request
    const versionGetResponse = await client.sendRequest({
        url: URL,
        path: "/api/status/version",
        method: "GET",
        headers: headers
    });

    // Generated Assertions
    expect(versionGetResponse.statusCode, 'status code').toBe(200);
    expect(checkSchema(versionGetResponse, expectedVersionGetResponseBody), 'schema').toBeTruthy();
    expect(getResponseValue(versionGetResponse, "nodeVersion"), 'value').not.toBeNull();
    expect(getResponseValue(versionGetResponse, "version"), 'value').not.toBeNull();
    expect(getResponseValue(versionGetResponse, "version"), 'version').toBe("development");
    expect(getResponseValue(versionGetResponse, "nodeVersion"), 'nodeVersion').toMatch(/^v\d+\.\d+\.\d+$/);
});
