// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { TImmutableDBKeys } from "./models";

export const SecretFavoritesSchema = z.object({
  id: z.string().uuid(),
  userId: z.string().uuid(),
  secretId: z.string().uuid(),
  projectId: z.string(),
  createdAt: z.date().nullable().optional()
});

export type TSecretFavorites = z.infer<typeof SecretFavoritesSchema>;
export type TSecretFavoritesInsert = Omit<z.input<typeof SecretFavoritesSchema>, TImmutableDBKeys>;
export type TSecretFavoritesUpdate = Partial<Omit<z.input<typeof SecretFavoritesSchema>, TImmutableDBKeys>>;
