// Generated by Skyramp v1.3.25 on 2026-06-03 17:05:23.744546377 +0000 UTC m=+492.168623234
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output admin_version_node_build.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/ui \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/admin_version_node_build_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(105000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const errors: Error[] = [];
    page.on('pageerror', err => errors.push(err));

    await page.goto("http://localhost:8080/login");
    await page.waitForLoadState('networkidle');
    await page.waitForTimeout(2000);
    await page.getByRole("textbox", { name: "Enter your email..." }).fill("admin@test.com");
    await page.getByRole("textbox", { name: "Enter your password..." }).fill("Password123!");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    await page.waitForLoadState('networkidle');
    await page.goto("http://localhost:8080/admin");
    await page.waitForLoadState('networkidle');
    await page.waitForSelector("text=Node Version");
    await expect(page).toHaveURL(/\/admin/);
    await expect(page.getByText("v22.22.0")).toContainText("v22.22.0");
    await expect(page.getByText(/\d+\/\d+\/2026/)).toContainText("2026");
    expect(errors).toHaveLength(0);
});
