// Generated by Skyramp v1.3.25 on 2026-06-03 17:05:21.338654626 +0000 UTC m=+489.762731503
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output admin_server_version_card.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/ui \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/admin_server_version_card_trace.zip

// Import of required libraries
import { test, expect, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(447000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const errors: Error[] = [];
    page.on('pageerror', err => errors.push(err));

    await page.goto("http://localhost:8080/login");
    // Wait for network activities to finish
    await page.waitForTimeout(7500);


    const playwrightRequest0: Record<string, any> = {
        "email": "admin@test.com",
        "password": "Password123!"
    };

    await page.getByRole("textbox", { name: "Enter your email..." }).fill(getValue(playwrightRequest0, "email"));
    await page.getByRole("textbox", { name: "Enter your password..." }).fill(getValue(playwrightRequest0, "password"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/v3/auth/login**");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    const response0 = await responsePromise0;
    expect(response0.status()).toBe(200);

    await page.goto("http://localhost:8080/admin");
    await page.waitForLoadState('networkidle');
    await page.waitForTimeout(2000);
    await page.goto("http://localhost:8080/login");
    await page.waitForLoadState('networkidle');
    await page.goto("http://localhost:8080/admin");
    await page.waitForLoadState('networkidle');
    await page.waitForSelector("text=Server Version");
    await expect(page).toHaveURL(/\/admin/);
    await expect(page.getByText("v22.22.0")).toContainText("v22.22.0");
    await expect(page.getByText(/\d+\/\d+\/2026/)).toContainText("2026");
    expect(errors).toHaveLength(0);
});
